[build]
builder = "nixpacks"
buildCommand = "npm --prefix server install && npm --prefix client install && npm run build"

[deploy]
startCommand = "npm --prefix server run start"
restartPolicyType = "on_failure"
